### ISSUE TITLE
Why not use resnet as backbone?

### ISSUE THREAD

**Issue by lucy3589** [otkupjnoz/mlosr#1]
hello,I have no idea about Why not use resnet as backbone? Please tell me? thanks!

**Comment by otkupjnoz** [comment]
Hi, I definitely agree that using resnet as backbone is an excellent idea. However, for my experiments in the paper I directly compared with another interesting approach for open-set (to appear in CVPR19 and found here: https://arxiv.org/pdf/1812.04246.pdf). Their experiments on CIFAR-10 used VGG and DenseNet backbone and to be consistent with that, I also use those network architecture.

I am sure you can definitely use ResNet backbone, but might have to make minor modification in the decoder network (to adjust for the change in dimension of features extracted from ResNet). Thank you for your interest in our work, I hope you are able to run the code for densenet and VGG without any error.

**Comment by lucy3589** [comment]
> Hi, I definitely agree that using resnet as backbone is an excellent idea. However, for my experiments in the paper I directly compared with another interesting approach for open-set (to appear in CVPR19 and found here: https://arxiv.org/pdf/1812.04246.pdf). Their experiments on CIFAR-10 used VGG and DenseNet backbone and to be consistent with that, I also use those network architecture.
> 
> I am sure you can definitely use ResNet backbone, but might have to make minor modification in the decoder network (to adjust for the change in dimension of features extracted from ResNet). Thank you for your interest in our work, I hope you are able to run the code for densenet and VGG without any error.

Thanks for your reply. I understand now.
